name: Advanced testing with Github Actions 
on:
  schedule:
  - cron:  '0 3 * * SUN'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    strategy:
        matrix:
            python-version: [3.8.x, 3.9.x, 3.10.x, 3.11.x]
            os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}    

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.12.5
        uses: actions/setup-python@v1
        with: 
          python-version: 3.12.x
          
      - name: install packages and dependencies
        run: |
          make install
      - name: lint with pylint
        run: |
          make lint
      - name: test with pytest
        run: |
          make test
      - name: format with black 
        run: |
          make format
